### ISSUE TITLE
[Bug]：choose 可以標記到所有使用者

### ISSUE THREAD

**Issue by sus2790** [HiZollo/Junior-HiZollo#51]
### 預期效果

z!choose @everyone @here
AllowMention應該被設定為 `[]`

### 實際行為

choose沒有設定AllowMention
見：https://discord.com/channels/572733182412193792/774937521275666432/1142745070630621327

### 有問題的指令

choose 的文字指令 (斜線指令不會)

### 伺服器 ID

572733182412193792

### 你的名字

``#2790 (pan._.python)

### 其它資訊

大概就把choose的AllowMention關掉

**Comment by AWeirdScratcher** [comment]
bro you pinged @ everyone and @ here on github 😱

**Comment by dragonyc1002** [comment]
既然你已經開 Pull Request 這邊就可以 close 吧。

**Comment by sus2790** [comment]
我是想說等PR關了這裡在關

**Comment by kyometori** [comment]
> 既然你已經開 Pull Request 這邊就可以 close 吧。

PR Merged 了這邊再關。
